(() => {
  'use strict';
  const VALID_LANGUAGES = ['ja', 'en', 'zh-TW', 'ko', 'ru'];
  const CONSENT_KEY = 'memoriopolis_analytics_consent';
  const copy = {
    ja: { status: n => `第${['一','二','三','四','五','六'][n-1]}景 / 六景`, s1_title:'同じ名前', s1a:'一覧の二行目にも、一行目と同じ送り主の名前が入った。', s1b:'受け取る側から見れば、二つの通知に違いはなかった。', s1c:'けれど、経路を書き加えると、二つの線は最初から別の場所にあった。', s2_title:'古い申請', s2a:'「問題がないことは、確かめられたの？」', s2b:'私は先に尋ねた。', s2c:'「少し違います」', s2d:'一つひとつの変更は正式だった。けれど、最初から現在まで一つにつないだ記録はなかった。', s2e:'「継ぎ目です」', s3_title:'引き継がれた仕組み', s3a:'古地層では、文書と会話と作業結果が、同じ時間の中へ折り重なっていた。', s3b:'かつて、誰かがその経路を正しいものとして設計したという記憶だった。', s4_title:'外部の道', s4a:'業務システムが作った通知は、市の外にある配信サービスへ渡されていた。', s4b:'経路は、ひとつの制度の中で終わらない。', s5_title:'正規だが証明できない', s5a:'誰か一人が嘘をついているわけではない。どこか一つが壊れているわけでもない。', unverified:'未確認', s5b:'「正しさが、一つの場所にないのです」', s6_title:'証明されたもの', s6a:'一つは、正規だと知っているのに、うまく証明できない。', s6b:'もう一つは、正規だと証明できるのに、すぐには信じられない。', s6c:'「同じ信じ方でよいのでしょうか」', closing:'証明できない正しさと、信じられない証明が、同じ画面に並んでいた。' },
    en: { status:n=>`Scene ${n} / 6`, s1_title:'The Same Name', s1a:'The second row of the list bore the same sender name as the first.', s1b:'To anyone receiving them, the two notifications looked no different.', s1c:'But once their routes were added, the two lines began in different places.', s2_title:'The Old Application', s2a:'“Have we verified that there’s no problem?”', s2b:'I asked before she could.', s2c:'“Not quite.”', s2d:'Each change was authorized on its own, but no single record connected them from the beginning to the present.', s2e:'“The seams.”', s3_title:'The Inherited System', s3a:'In the old strata, documents, conversations, and work results lay folded together within the same span of time.', s3b:'It was the memory that someone had once designed the route to be valid.', s4_title:'The External Route', s4a:'The notification was passed to a delivery service outside the city.', s4b:'A route does not end within a single institution.', s5_title:'Authorized, Yet Unproven', s5a:'No one person was lying. No single part was broken.', unverified:'Unverified', s5b:'“The validity is not all in one place.”', s6_title:'What Could Be Proved', s6a:'One was known to be legitimate, yet could not be properly established.', s6b:'The other could be established as legitimate, yet could not immediately be trusted.', s6c:'“Should we trust them in the same way?”', closing:'A validity that could not be proved and a proof that could not be trusted stood side by side on the same screen.' },
    'zh-TW': { status:n=>`第${['一','二','三','四','五','六'][n-1]}景／六景`, s1_title:'相同的名字', s1a:'清單的第二列，也填入了和第一列相同的寄件者名稱。', s1b:'從收件者的角度來看，兩封通知沒有任何差別。', s1c:'然而，將路徑補進清單之後，兩條線從一開始便位於不同的地方。', s2_title:'舊申請', s2a:'「沒有問題這件事，已經確認過了嗎？」', s2b:'我搶在她之前問道。', s2c:'「有一點不一樣。」', s2d:'每一項變更都是正式的，卻沒有紀錄把它們從最初一路連到現在。', s2e:'「接縫。」', s3_title:'被承接的機制', s3a:'文件、交談和工作成果，層層摺疊在同一段時間之中。', s3b:'那是一段記憶，記得曾經有人將那條路徑設計成正確的事物。', s4_title:'外部的路', s4a:'業務系統產生的通知，會被交給市外的傳送服務。', s4b:'路徑不會終止於單一制度之內。', s5_title:'正式，卻無法證明', s5a:'並不是有哪一個人在說謊，也不是有哪一個地方壞掉了。', unverified:'尚未確認', s5b:'「正確性不在同一個地方。」', s6_title:'被證明的事物', s6a:'一封明知是正式的，卻無法順利證明。', s6b:'另一封能夠證明是正式的，卻無法立刻相信。', s6c:'「可以用同一種方式相信它們嗎？」', closing:'無法證明的正確，與無法相信的證明，並列在同一個畫面上。' },
    ko: { status:n=>`제${n}경 / 6경`, s1_title:'같은 이름', s1a:'목록의 두 번째 줄에도 첫 번째 줄과 같은 발신자의 이름이 들어갔다.', s1b:'받는 사람의 눈에는 두 알림 사이에 아무런 차이도 없었다.', s1c:'하지만 경로를 덧붙이자 두 선은 처음부터 서로 다른 곳에 있었다.', s2_title:'오래된 신청', s2a:'「문제가 없다는 건 확인됐나요?」', s2b:'나는 그녀보다 먼저 물었다.', s2c:'「조금 달라요.」', s2d:'하나씩 보면 모두 정식 변경이었지만, 처음부터 현재까지 하나로 이어 놓은 기록은 없었다.', s2e:'「이음새예요.」', s3_title:'이어받은 구조', s3a:'고지층에서는 문서와 대화와 작업 결과가 같은 시간 속에 겹겹이 접혀 있었다.', s3b:'한때 누군가가 그 경로를 올바른 것으로 설계했다는 기억이었다.', s4_title:'외부의 길', s4a:'업무 시스템이 만든 알림은 도시 밖의 전송 서비스로 넘겨지고 있었다.', s4b:'경로는 하나의 제도 안에서 끝나지 않는다.', s5_title:'정식이지만 증명할 수 없는 것', s5a:'누군가 한 사람이 거짓말을 하는 것도, 어딘가 한 곳이 고장 난 것도 아니었다.', unverified:'미확인', s5b:'「올바름이 한곳에 있지 않은 거예요.」', s6_title:'증명된 것', s6a:'하나는 정식이라고 알고 있지만 제대로 증명할 수 없다.', s6b:'다른 하나는 정식이라고 증명할 수 있지만 곧바로 믿을 수 없다.', s6c:'「같은 방식으로 믿어도 되는 걸까요?」', closing:'증명할 수 없는 올바름과 믿을 수 없는 증명이 같은 화면에 나란히 놓여 있었다.' },
    ru: { status:n=>`Сцена ${n} / 6`, s1_title:'То же имя', s1a:'Во второй строке списка появилось то же имя отправителя, что и в первой.', s1b:'Для получателя между двумя уведомлениями не было никакой разницы.', s1c:'Но после добавления маршрутов оказалось, что две линии с самого начала находились в разных местах.', s2_title:'Старая заявка', s2a:'«А то, что проблем нет, уже проверили?»', s2b:'Я спросил раньше неё.', s2c:'«Немного не так».', s2d:'Каждое изменение было официальным, но ни одна запись не соединяла их от начала до настоящего.', s2e:'«Швов».', s3_title:'Унаследованный механизм', s3a:'В древних слоях документы, разговоры и результаты работы наслаивались внутри одного времени.', s3b:'Это была память о том, что когда-то кто-то спроектировал этот маршрут как правильный.', s4_title:'Внешний путь', s4a:'Уведомление передавалось службе доставки за пределами города.', s4b:'Маршрут не заканчивается внутри одного института.', s5_title:'Официально, но недоказуемо', s5a:'Ни один человек не лгал. Ни одна отдельная часть не была сломана.', unverified:'Не проверено', s5b:'«Правильность не находится в одном месте».', s6_title:'То, что было доказано', s6a:'Одно считалось официальным, но это нельзя было как следует доказать.', s6b:'Официальность другого можно было доказать, но ему нельзя было сразу поверить.', s6c:'«Следует ли верить им одинаково?»', closing:'Правильность, которую нельзя было доказать, и доказательство, которому нельзя было поверить, находились рядом на одном экране.' }
  };
  const emaki = document.getElementById('emaki');
  const progress = document.getElementById('progress-bar');
  const status = document.getElementById('scene-status');
  const panels = [...document.querySelectorAll('[data-scene]')];
  let currentLanguage = 'ja';
  let lastScene = 1;
  let ticking = false;
  function analyticsReady(){ try{return localStorage.getItem(CONSENT_KEY)==='granted' && typeof window.gtag==='function';}catch{return false;} }
  function sendEvent(name, params){ if(analyticsReady()) window.gtag('event', name, params); }
  function languageFromHash(){ const value=decodeURIComponent(location.hash.replace(/^#/,'')); return VALID_LANGUAGES.includes(value)?value:'ja'; }
  function applyLanguage(language,userInitiated=false){ if(!copy[language]) return; const previous=currentLanguage; currentLanguage=language; document.documentElement.lang=language; document.querySelectorAll('[data-i18n]').forEach(el=>{ const value=copy[language][el.dataset.i18n]; if(value) el.textContent=value; }); document.querySelectorAll('[data-language-button]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.languageButton===language))); if(location.hash!==`#${language}`) history.replaceState(null,'',`#${language}`); updateProgress(); if(userInitiated&&previous!==language) sendEvent('language_switch',{section_id:'section11',from_language:previous,to_language:language}); }
  function currentScene(){ const center=emaki.scrollLeft+emaki.clientWidth/2; let choice=panels[0]; let distance=Infinity; panels.forEach(panel=>{ const d=Math.abs(panel.offsetLeft+panel.offsetWidth/2-center); if(d<distance){distance=d;choice=panel;} }); return Number(choice?.dataset.scene||1); }
  function updateProgress(){ const max=Math.max(1,emaki.scrollWidth-emaki.clientWidth); const ratio=Math.min(1,Math.max(0,emaki.scrollLeft/max)); progress.style.width=`${ratio*100}%`; const scene=currentScene(); status.textContent=copy[currentLanguage].status(scene); if(scene!==lastScene){lastScene=scene;sendEvent('emaki_scene_view',{section_id:'section11',scene_number:scene,language:currentLanguage});} ticking=false; }
  function requestUpdate(){ if(!ticking){ticking=true;requestAnimationFrame(updateProgress);} }
  function scrollByPanel(direction){ emaki.scrollBy({left:direction*emaki.clientWidth*.82,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}); }
  document.querySelectorAll('[data-language-button]').forEach(b=>b.addEventListener('click',()=>applyLanguage(b.dataset.languageButton,true)));
  document.querySelectorAll('[data-scroll-direction]').forEach(b=>b.addEventListener('click',()=>scrollByPanel(b.dataset.scrollDirection==='forward'?1:-1)));
  document.querySelectorAll('[data-open-production-notes]').forEach(link=>link.addEventListener('click',()=>sendEvent('open_production_notes',{section_id:'section11',source:link.dataset.source||'unknown'})));
  emaki.addEventListener('scroll',requestUpdate,{passive:true});
  emaki.addEventListener('keydown',event=>{ if(event.key==='ArrowRight'){event.preventDefault();scrollByPanel(1);} if(event.key==='ArrowLeft'){event.preventDefault();scrollByPanel(-1);} if(event.key==='Home'){event.preventDefault();emaki.scrollTo({left:0,behavior:'smooth'});} if(event.key==='End'){event.preventDefault();emaki.scrollTo({left:emaki.scrollWidth,behavior:'smooth'});} });
  window.addEventListener('hashchange',()=>applyLanguage(languageFromHash(),false));
  window.addEventListener('resize',requestUpdate,{passive:true});
  applyLanguage(languageFromHash(),false); updateProgress();
})();
